### ISSUE TITLE
Is there any plan to support the basic authentication? [feature request]

### ISSUE THREAD

**Issue by panegyrize** [Ansersion/myRtspClient#12]
Current repository only supports the digest authentication, which is also more complicated and heavily used in the practical world. However, in some rare cases where IPCs would need the basic authentication, the library fails to pull the data out. Is there a plan to support this? Thanks.

**Comment by Ansersion** [comment]
Just now I committed the code to try to support basic authentication.
I didn't have the environment to test the feature thoroughly, so I made it suspended.
If the newest code doesn't work, I will appreciate it that you could printf the string 'RtspResponse' in RtspClient::CheckAuth for me to help improve the lib.
Thanks.

**Comment by panegyrize** [comment]
Great, thanks for your prompt action. I will update the code and test it with the IPCs that adopt basic authentication. I will post the result here. Thanks.

**Comment by panegyrize** [comment]
Ansersion,

I tested the library with the camera that uses the basic authentication and it works. Thanks for the work and I am closing the issue.

I've also seen some other issues which I will illustrate separately in another thread.
