### ISSUE TITLE
Switching video memory is increasing!

### ISSUE THREAD

**Issue by cafecai** [Ansersion/myRtspClient#19]
Our project needs to switch video streams. When doing stress tests, we find that memory is constantly increasing.The test code is as follows:

HI_VOID * play_rtsp(HI_VOID *pArgs)
{
	
	RtspClient Client;
	string RtspUri(pstVdecSend->cFileName);	
	const size_t BufSize=pstVdecSend->s32MinBufSize;
	HI_U8 *pbuf;
	size_t size = 0;

	pbuf=(HI_U8*)malloc(BufSize);
	while(1)
	{
		Client.SetURI(RtspUri);
		Client.DoDESCRIBE();
		Client.ParseSDP();
		Client.DoSETUP("video", true);
		Client.SetVideoByeFromServerClbk(ByeFromServerClbk);
		printf("start PLAY\n");
		//printf("SDP: %s\n", Client.GetSDP().c_str());
		Client.DoPLAY("video");
		
		
		printf("start TEARDOWN\n");
		Client.DoTEARDOWN();
		sleep(1);
	}
	free(pbuf);
	return (HI_VOID *)HI_SUCCESS;
}

**Comment by Ansersion** [comment]
I am sorry for any inconvenience I've caused. 
I've fixed the bug just now.

**Comment by cafecai** [comment]
After modifying the code, it was tested for 2 days and it worked fine. Thank you
